### PR TITLE
Feature: Add configurable spacing to Input, ShortText and LongText

### PR DESCRIPTION
**Pull request by NduatiK**

### CODE REVIEW

**Comment by NduatiK** [comment]
[The input fields are too big](https://trello.com/c/roUepHzA/101-the-input-fields-are-too-big)

**Comment by NduatiK** [comment]
The `Select` view uses spaceMultiples instead of  `verticalPadding` and `horizontalPadding`. Would we prefer that for the Input fields instead?

---
```
{
    spacerMultiples :
        { y : \Size -> Float
        , x : \Size -> Float
        }
}
```

**Comment by NduatiK** [comment]
[Makes spacers configurable for form field views](https://trello.com/c/6XhFPn20/24-makes-spacers-configurable-for-form-field-views)

**Review by dhruvio — APPROVED** [review]
LGTM 🎉

**Comment by dhruvio** [comment]
@NduatiK So I realized that the `spacerMultiples` should be a part of the widget's `Theme` instead of a top-level option (like the `Select` view). Sorry, missed that in my original review.

**Pull request merged**
